name: Bicep Code Run

##### Uncomment and Comment out the Workflow Dispatch Below ####
# on:
#   push:
#     branches: 
#     #- master
#      - none
#     paths-ignore:
#     - "*.md"
#     - main
#     - master
#   pull_request:
#     branches: 
#     - master
# permissions:
#   id-token: write
#   contents: read

##### Using Workflow Dispatch #####
on:
  #[push, workflow_dispatch]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Bicep Pipeline Test'
        required: false
        type: boolean
      environment:
        description: 'Environment to run Bicep GitHub Tests'
        type: environment
        required: false
permissions:
   id-token: write
   contents: read
   pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Run Bicep
    - name: Deployment
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        name: Test
        location: eastus2
        scope: subscription
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template-file: ./main.bicep
        parameters-file: ./parameters/github-bicep-var.bicepparam